QuTech-Delft/OpenSquirrel

- opensquirrel/gates.py
- opensquirrel/mckay_decomposer.py
The main optimization is the replacement of `np.cross` with a direct calculation for 3d vectors. 
```
%timeit myCircuit.decompose_mckay()
1.24 ms ± 54 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
In [4]: %timeit myCircuit.decompose_mckay()
686 µs ± 79 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
@pablolh
> Optimize McKay decomposer

- opensquirrel/circuit.py
- opensquirrel/common.py
- opensquirrel/default_gates.py
- opensquirrel/mckay_decomposer.py
- opensquirrel/merger.py
- opensquirrel/replacer.py
- opensquirrel/squirrel_ir.py
- test/ir_equality_test_base.py
- test/test_integration.py
- test/test_mckay_decomposer.py
- test/test_merger.py
- test/test_replacer.py
- Circuit.merge_single_qubit_gates
- mcKay decomposer is now only the decomposition
- Circuit.decompose is introduced, pass it the McKay decomposer
> Create merge pass

- opensquirrel/cnot_decomposer.py
- opensquirrel/merger.py
- test/test_cnot_decomposer.py
- test/test_integration.py
Fix https://github.com/QuTech-Delft/OpenSquirrel/issues/99
This decreases gate count for e.g CNOT decomposition of CZ (which then uses a single CNOT sandwiched by 2 Hadamard gates).
Thanks to @prince-ph0en1x for pointing towards relevant literature, namely https://arxiv.org/abs/quant-ph/9503016
> Add special case for single-CNOT decomposition of controlled-U

- test/decomposer/test_cnot_decomposer.py
- test/decomposer/test_mckay_decomposer.py
- test/exporter/test_quantify_scheduler_exporter.py
- test/ir_equality_test_base.py
- test/mapper/test_qubit_remapper.py
- test/merger/test_merger.py
- test/parser/libqasm/test_libqasm.py
- test/reindexer/test_qubit_reindexer.py
- test/test_circuit_matrix_calculator.py
- test/test_integration.py
- test/test_ir.py
- test/test_replacer.py
- test/test_writer.py
- test/test_zyz_decomposer.py
- test/utils/test_matrix_expander.py
This pull request converts the `unittest` style tests to the `pytest` format. All tests have been updated with the exception of the tests for the quantify scheduler. These tests should probably be redesigned to use `quantify_scheduler` instead of mocking its behavior.
Closes #215
> 215 unittest to pytest

- opensquirrel/circuit_builder.py
- test/test_circuit_builder.py
This addition solves the bug where a user can add a Gate or Measurement which surpasses the qubit or bit index of the given circuit.
> 83 fix non existing qubit index not giving error

- opensquirrel/circuit_builder.py
- test/test_circuit_builder.py
Use `deepcopy` to copy the `IR` and `RegisterManager` of the builder instead of using a reference.
Added a test for this behavior as well.
> Cqt 76 linked ir between circuit and circuit builder

- poetry.lock
- pyproject.toml
> CQT 39: check if ANTLR4 dependency is still required (otherwise, remove)

- opensquirrel/exporter/quantify_scheduler_exporter.py
- test/exporter/test_quantify_scheduler_exporter.py
- test/mapper/test_general_mapper.py
- test/mapper/test_qubit_remapper.py
- test/merger/test_merger.py
- test/parser/libqasm/test_libqasm.py
- test/reindexer/test_qubit_reindexer.py
- test/test_circuit_matrix_calculator.py
- test/test_replacer.py
- test/writer/test_writer.py
All test that can use the `CircuitBuilder` now use the `CircuitBuilder` to build the circuits required for the tests.
The following tests were left untouched:
- Integration test
- Parser tests
- Measurement tests. Some of these tests are checking checking parsing of measurements from string (we might want to move those to the parsing tests)
- Register test. Named registers are not supported in the `CircuitBuilder`.
> Cqt 51 replace tests using c qasm strings with circuits generated through the circuit builder

- poetry.lock
- pyproject.toml
- test/merger/test_merger.py
- tox.ini
This pull request configures `tox`.
Testing and and type checking remain the same, but linting has been altered. Linting now uses `ruff`, with an extended list of selected linters options. All options that we currently do not comply with are commented out, but should be turned on at some point. This is an extended list indeed, but if we manage to comply with these rules we will have a uniform and well thought out codebase. More importantly, most style related issues will be resolved before a pull request is made, meaning that a review can focus much more on content than style.
Note that we don't use `isort`, since `ruff` can sort the imports for us.
> [CQT-58] Implement and configure tox

- opensquirrel/writer/writer.py
- test/writer/test_writer.py
Add a few tests.
Rename also some tests.
Rename `num_significant_digits` to `FLOAT_PRECISION` (for consistency with Quantify Scheduler exporter's `DEG_PRECISION`).
Change writer to always only output one single trailing newline.
> [CQT-50] Add extra tests to writers where needed

- opensquirrel/parser/libqasm/parser.py
Instead of switching from the default analyzer, we keep registering the instructions in libQASM and also have them in the OpenSquirrel gate/measurement libraries.
- Removed the TODO in the `_create_analyzer` method in the module `parser.py`.
> Switch from Default Analyzer

- pyproject.toml
Asyncio mode not needed as it determines the default event loop scope of asynchronous fixtures.
> [CQT-167] Remove asyncio mode

- opensquirrel/ir.py
- test/test_ir.py
* Verify dataclasses using __post_init__
* Restructure tests and remove try-exceptions
* Fix typos
---------
> [CQT 126] Verify dataclasses using __post_init__ (#319)

- pyproject.toml
- tox.ini
- Removed `black` from the `pyproject.toml` and `tox.ini` files.
- Removed `sympy` from the `docs` group
The `IPython` and `sympy` packages are necessary in the `dev` group as they are used to test the examples.
> [CQT-166] Review required dependencies

- opensquirrel/ir.py
- test/test_ir.py
- Hashing of qubit and bit are no longer the same
- hash(Qubit(1)) != hash(Bit(1))
> [CQT 201] Incorrect hashing of qubit

- opensquirrel/exporter/quantify_scheduler_exporter.py
- test/test_integration.py
Changed using `list.insert(indx, data)` to using `list[indx] = data`
(this was changed before due to issues with MyPy, but because those issues had been dealt with in another way, using `insert` is not necessary, and apparently wrong)
> Fix bug list insert does not overwrite

- opensquirrel/default_gates.py
- test/decomposer/test_cnot_decomposer.py
- test/exporter/test_quantify_scheduler_exporter.py
- test/test_replacer.py
- Removed SWAP, sqrtSWAP, and CCZ from the `default_gates.py`
- Removed tests specifically involving these gates
> Remove unsupported gates from default gate set.

- poetry.lock
- pyproject.toml
- test/test_integration.py
- test/test_reset.py
pyproject.toml: update libqasm to version 0.6.9.
test_integration.py: change 'reset' to 'reset q' in test_hectoqubit_backend_allxy.
test_reset.py: remove test_reset_all.
> [CQT-272] Integrate libQASM 0.6.9 into OpenSquirrel

- opensquirrel/passes/decomposer/aba_decomposer.py
- opensquirrel/passes/decomposer/cnot_decomposer.py
Move `_set_axes_values` out of `get_decomposition_angles`.
Rename `_set_axes_values` to `_set_a_b_c_axes_value`s.
Convert `_calculate.*` functions back to code with a comment.
Change `get_decomposition_angles` parameter order.
Update doc for `get_decomposition_angles` and `_set_a_b_c_axes_values`.
> Rewrite `get_decomposition_angles` (2)

- opensquirrel/passes/router/__init__.py
- opensquirrel/passes/router/routing_checker.py
- test/router/test_routing_checker.py
- test/test_integration.py
- change start node type from int to string of connectivity
- change input argument name of RoutingChecker to connectivity
- add `__init__.py` to routing module
- update spin2plus integration test to match compiler config
> [CQT-312] Align compiler config

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- Relax NumPy version number requirement to >=1.26.
- Add entry to Changelog
> [CQT-318] Relax numpy version dependency

- CHANGELOG.md
- opensquirrel/writer/writer.py
- pyproject.toml
- test/writer/test_writer.py
- Added `"qubit0"` and `"qubit1"` to the `qubit_function_keys`
- Added test to check if SWAP is properly writen
> Fix bug in writer for SWAP instruction.

- pyproject.toml
- tox.ini
- Move pytest config from pyproject.toml to tox.ini.
> [CQT-410] Move pytest options from pyproject.toml to tox.ini to enable debugging
